[build]
  publish = "."

[build.environment]
  ECODILA_ENV = "TEST"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
